### PR TITLE
add napalm_traceroute task similiar to napalm_ping task

### PR DESCRIPTION
**Pull request by MatthiasGabriel**
Added additional napalm_traceroute task similiar to napalm_ping task

Currently I did not add any testcase, because I do not know how you prefer it as there is little functionality in the task itself and there is not test for the napalm_ping task either.
I thought about adding mocked data similar to the other task tests to test that the integration with napalm works. What do you think?

### CODE REVIEW

**Comment by MatthiasGabriel** [comment]
Maybe rename the dest parameter to destination to use the same terms as in napalm.
But then ping and traceroute would use different parameters.
What do you think?

**Comment by dbarrosop** [comment]
hello, sorry for the late reply. I’d suggest trying to be consistent with napalm’s parameters. Eventually we could try doing the same with the existing ones.

Re tests, something like [this](https://github.com/nornir-automation/nornir_napalm/blob/master/docs/source/tutorials/napalm_cli.ipynb) would be ideal as it serves as both documentation and tests (mostly docs and to avoid regressions)

**Comment by MatthiasGabriel** [comment]
Hi,
I changed the parameter to match napalms naming schema and added a jupyter notebook as wished.
The problem hereby is that for this to work a small change in napalm is necessary.
I opened another PR in the napalm repo: [Mock traceroute](https://github.com/napalm-automation/napalm/pull/1326)

**Comment by dbarrosop** [comment]
Ok, good job and thanks for the effort. Everything looks good so let's wait a bit until napalm's PR has been approved and merged.

**Comment by dbarrosop** [comment]
BTW, I fixed the CI so you will need to rebase

**Comment by MatthiasGabriel** [comment]
@dbarrosop is anything missing? I think the pr got merged :)

**Comment by dbarrosop** [comment]
Apologies for the delay, for some reason I can't re-run the checks on this PR, would you mind trying to do so? Sending a new dummy commit, squashing, or something of the like should work.

**Comment by MatthiasGabriel** [comment]
Hi @dbarrosop 
I updated the readme and through it triggered the pipeline.
The tests AND the linter are now failing.
Could it be that the tests are failing because of an outdated napalm version or are they just incorrect(thats quite possible :) )

**Comment by dbarrosop** [comment]
Looks like something changed in the base image for the CI and it's missing some dependencies. Could you add the following:

```
- name: Install xml dependencies
  run: sudo apt-get install libxml2-dev libxslt-dev
```

in this file? https://github.com/nornir-automation/nornir_napalm/blob/master/.github/workflows/main.yaml

You will have to add it a couple of times right above the action named "Installing dependencies". If that doesn't work I will take a look myself.

**Comment by MatthiasGabriel** [comment]
@dbarrosop I guess we have to wait for the next napalm release and then update the napalm version.

**Comment by dbarrosop** [comment]
Glad to see it works with the development branch. I just checked and last release of napalm was in Sept 2020, maybe someone should poke them to do a release :P

**Comment by ktbyers** [comment]
@MatthiasGabriel Are you still working on this?

**Comment by MatthiasGabriel** [comment]
@ktbyers No not really. I think we can close this. What do you think @ubaumann

**Comment by ktbyers** [comment]
I will go ahead and close this PR. We can re-open it if someone wants to work on it.

**Pull request closed without merging**
