### PR TITLE
Update dependencies and remove py3.6

### PR DESCRIPTION
**Pull request by ubaumann**
I updated the dependencies and removed Python 3.6 like it is in the `nornir` repository

### CODE REVIEW

**Comment by dbarrosop** [comment]
yeah, that's what I was complaining about on twitter...

image

**Comment by ubaumann** [comment]
I totally understand you but I will figure it out somehow ;)
I think it was anyway not bad to update the dependencies

**Comment by dbarrosop** [comment]
Looks like after your last commit everything works fine with the exception of py3.10. If you don't want to spend too much energy on this I think it's fine if you remove py3.10 for now.

Awesome work btw, you made my day :P

**Comment by ubaumann** [comment]
> Looks like after your last commit everything works fine with the exception of py3.10. If you don't want to spend too much energy on this I think it's fine if you remove py3.10 for now.
> 
> Awesome work btw, you made my day :P

Thanks! I am happy to help.

I hope the junos-eznc update solves the py3.10 issue and otherwise I will remove it from the workflow for now. I saw napalm has in the develop branch also py3.10 support and the nornir core as well so it would be nice to have it in this plugin as well

**Comment by ubaumann** [comment]
@dbarrosop I don't want to stress you. I just rememberd this PR and was thinking I will ping you but no rush. I am forgeting about stuff all the time if I don't do it direclty :)

**Comment by ktbyers** [comment]
LGTM.

**Pull request merged**
