### PR TITLE
pass encoding to napalm_cli for eos

### PR DESCRIPTION
**Pull request by siguroot**
In regards to Issue #50, need to ability to toggle between 'text' and 'json' encoding for EOS platform.

### CODE REVIEW

**Comment by dbarrosop** [comment]
You can just push a commit fixing it. One comment regarding:

```
encoding: Optional[str] = "text"
```

Given you are setting a default value I think that `encoding: str = "text"` should suffice. `Optional` is mostly to indicate that something is allowed to be `None` which I don't think it's the case.

**Comment by siguroot** [comment]
Thanks for the wisdom.  And yes, completely concur.  Latest commit reflects your suggestions.

**Comment by dbarrosop** [comment]
@ktbyers what are your thoughts on this? I am not sure how I feel about `napalm_cli` taking explicit argument that are platform dependant. Maybe just allow for `**kargs` and push the responsibility to the user?

**Comment by siguroot** [comment]
Are you thinking something like this?

```
def napalm_cli(task: Task, commands: List[str], **kwargs) -> Result:
    """
    Run commands on remote devices using napalm

    Arguments:
      commands: commands to execute
      encoding: pass 'text' or 'json' to napalm cli
    Returns:
      Result object with the following attributes set:
        * result (``dict``): result of the commands execution
    """
    device = task.host.get_connection(CONNECTION_NAME, task.nornir.config)
    
    try:
      result = device.cli(commands, **kwargs)
    except NotImplementedError:
      result = device.cli(commands)
```

I agree with your approach.  Seeing as how the goal of napalm is to be as agnostic as possible.  I can push another commit, but I'll wait to see what Kirk says.

**Comment by ktbyers** [comment]
Yeah, let's definitely use **kwargs.

Format would be:

```
https://github.com/nornir-automation/nornir_napalm/blob/master/nornir_napalm/plugins/tasks/napalm_get.py#L15
```

Use the type hints `Any` (which you will probably need to import as well).

Also make sure your linting is passing.

**Comment by siguroot** [comment]
I decided to not put in error handling (i alluded to this earlier in a comment) as if it was me running this, I would want it to choke so I could correct the problem.  Also, fixed my linting problems (i think :-/).

**Comment by dbarrosop** [comment]
LGTM, @ktbyers any comments? Otherwise, feel free to merge.

**Pull request merged**
