### PR TITLE
Create new release to update napalm to version 4.x and netmiko to 4.x

### PR DESCRIPTION
**Pull request by ktbyers**
I will release a nornir_netmiko new version that requires Netmiko 4.x at about the same time.

### CODE REVIEW

**Comment by ktbyers** [comment]
I tested both this and the new version of nornir_netmiko pretty extensively in my lab environment.

**Comment by ktbyers** [comment]
Here is the corresponding nornir_netmiko pull request (for new release of nornir_netmiko):

https://github.com/ktbyers/nornir_netmiko/pull/40

**Comment by dbarrosop** [comment]
Thanks! I released it for you: https://pypi.org/project/nornir-napalm/#history

**Comment by ktbyers** [comment]
Great thanks. I will try to release nornir_netmiko today.

**Pull request merged**
