### PR TITLE
Add commit-confirm support

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
I need to think about/test these workflows a bit for various use cases.

**Comment by ktbyers** [comment]
On hold pending merge of PR #46 and then I need to rebase and fix the tests (as tests depending on #46)

**Comment by dbarrosop** [comment]
Feel free to ping me when this is ready for review.

**Comment by ktbyers** [comment]
@dbarrosop Okay, this should be good to go now.

**Review by dbarrosop — APPROVED** [review]

**Comment by dbarrosop** [comment]
Nice! +1

**Pull request merged**
