### PR TITLE
Add revert_in parameter to napalm_configure.

### PR DESCRIPTION
**Pull request by Kircheneer**
Add a `revert_in` parameter to `nornir_napalm.plugins.tasks.napalm_configure.napalm_configure`. Since NAPALM itself handles cases where this isn't supported I believe these two lines are all that need to change.

### CODE REVIEW

**Comment by ktbyers** [comment]
Have you tested the workflow using `nornir_napalm`, fully commit using the revert timer, abort immediately for a pending commit, and revert using the timeout?

I just want to make sure we have the way to actualize all this with the plugin.

**Comment by Kircheneer** [comment]
> abort immediately for a pending commit

is the only one I have not tested. I will get back to you (also with a successful pipeline).

**Comment by gcasella** [comment]
Just wanted to get an update on this PR

**Comment by dbarrosop** [comment]
Would you mind fixing the tests? I think it's just `black` that is broken. Otherwise, LGTM.

**Comment by Kircheneer** [comment]
I was not able to follow up on @ktbyers request yet but I did run black and push that, so @dbarrosop if that is enough, good to merge from my perspective.

**Comment by dbarrosop** [comment]
@ktbyers any concerns?

**Comment by gneville-ot** [comment]
Hi @dbarrosop , @ktbyers, @Kircheneer 

I noticed there was no way of being able to confirm a commit so I tested by adding a confirm_commit bool that is set to false by default within my own fork.

```
    if confirm_commit:
        device.confirm_commit()
    elif replace:
        device.load_replace_candidate(filename=filename, config=configuration)
    else:
        device.load_merge_candidate(filename=filename, config=configuration)
```

You can then call the confirm_commit by just calling it without any other parameters:

```
task.run(task=napalm_configure, name="Confirm Commit Confirmed", dry_run=False, replace=False, confirm_commit=True)
```

With the commit confirmed changes and the original changes in this PR I've tested the following:

- Invalid revert_in value error message bubbles up (set to 1 and complained only takes multiples of 60)
- Device will rollback if commit isn't confirmed within the revert_in value set
- Can send config in a commit confirmed mode and then confirm the commit
- Will error if there is already a lock on the configuration (configure exclusive)
- If there is already a pending commit with a revert time then it will apply the sent configuration on top, this is no different to to the behaviour seen on cli. The revert_in time gets reset to the timer sent in last.

I've opened #36 which has both sets of changes.

Please could you review?

**Comment by Kircheneer** [comment]
Thanks a lot @gneville-ot! I will close this out in favor of #36.

**Pull request closed without merging**
